_BASE_: "../faster_rcnn_R_101_FPN.yaml"
DATASETS:
  TRAIN: ('voc_2007_trainval_base1', 'voc_2012_trainval_base1')
  TEST: ('voc_2007_test_base1',)
OUTPUT_DIR: "outputs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_base1"