_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NAME: "TransformerROIHeads"
    BATCH_SIZE_PER_IMAGE: 1000
    SCORE_THRESH_TEST: 0.0
  ROI_BOX_HEAD:
    NAME: "MyFastRCNNTransformerHead"
  MY_ROI_BOX_HEAD:
    DIM_FEEDFORWARD: 1024
SOLVER:
  OPTIMIZER: "HYBRID"
  BOTTOM_UP_MULTIPLIER: 1.0
  TRANSFORMER_MULTIPLIER: 0.01
  WEIGHT_DECAY: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 5000
VIS_PERIOD: 500
