_BASE_: "Base-RCNN-FPN-TROI.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_myfpn_backbone"
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "smooth_l1+giou"
  MY_ROI_BOX_HEAD:
    USE_POSITION_ENCODING: True
SOLVER:
  TRANSFORMER_MULTIPLIER: 0.005
